name: Manual Retrain & Deploy

# Trigger: Manual button click (or Schedule)
on:
  workflow_dispatch:
    inputs:
      n_estimators:
        description: 'Number of trees'
        required: true
        default: '150'

jobs:
  # Job 1: Train the Model
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Train Model
      # We pass the input from the UI to the script arguments
      run: |
        # We need to quickly modify train.py to accept args or just run default
        # For this lab, let's just run the script, assuming it saves model.joblib
        python src/train.py
        
    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model.joblib
        retention-days: 1

  # Job 2: Package & Push
  deploy:
    needs: train # Wait for training to finish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          # Downloads to current directory, so Dockerfile finds it!
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-cicd:prod
